### ISSUE TITLE
Running the examples?

### ISSUE THREAD

**Issue by ChrisRus** [dogfessional/react-swipeable#29]
I cloned the repo, run the gulp script w/out error but notice that package.json does not register the run verb as suggested by the README.md in examples. Also, attempting to webpack the examples dir fails:

```
dr@tanager:~/code/HACK/community/react-swipeable/examples$ webpack
Hash: 1ec166479083b0a15a78
Version: webpack 1.12.2
Time: 253ms
   [0] multi main 28 bytes {0} [built] [1 error]
    + 1 hidden modules

ERROR in ./index.js
Module build failed: ReferenceError: Unknown plugin "transform-object-assign" specified in "base" at 0, attempted to resolve relative to "/home/cdr/code/HACK/community/react-swipeable/examples"
    at /home/cdr/node_modules/babel-core/lib/transformation/file/options/option-manager.js:206:17
    at Array.map (native)
    at Function.normalisePlugins (/home/cdr/node_modules/babel-core/lib/transformation/file/options/option-manager.js:182:20)
    at OptionManager.mergeOptions (/home/cdr/node_modules/babel-core/lib/transformation/file/options/option-manager.js:298:36)
    at OptionManager.init (/home/cdr/node_modules/babel-core/lib/transformation/file/options/option-manager.js:486:10)
    at File.initOptions (/home/cdr/node_modules/babel-core/lib/transformation/file/index.js:211:75)
    at new File (/home/cdr/node_modules/babel-core/lib/transformation/file/index.js:129:22)
    at Pipeline.transform (/home/cdr/node_modules/babel-core/lib/transformation/pipeline.js:48:16)
    at transpile (/home/cdr/node_modules/babel-loader/index.js:14:22)
    at /home/cdr/node_modules/babel-loader/lib/fs-cache.js:145:18
    at ReadFileContext.callback (/home/cdr/node_modules/babel-loader/lib/fs-cache.js:28:23)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
 @ multi main
```

What have I done wrong here? Thanks!

**Comment by hartzis** [comment]
when you clone the repo, and `cd` into `react-swipeable`. you then need to `cd` into `examples` folder and `npm install` there, then you can run `npm start`. Let me know if that works.

I just checked it on a fresh clone with node v4.2.6 and npm 3.6.0 and it worked fine

**Comment by ChrisRus** [comment]
Thanks - been busy will check this out.
